/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tresenraya;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.border.MatteBorder;

/**
 *
 * @author Alfonso
 */
public class JuegoTresEnRaya extends javax.swing.JFrame {

    // FALSE = CPU      2
    // TRUE = Usuario   1
    private boolean turno=true;
    private int[][] arrayJuego;
    private ImageIcon icono;
    
    /**
     * Creates new form JuegoTresEnRaya
     */
    public JuegoTresEnRaya() {
        initComponents();
        
        // Estilos del JFrame
        this.setSize(408, 530);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/tresenraya/images/icono.png")).getImage());
        
        // Bordes para las casillas del Grid
        Color colorBorde=new Color(153, 153, 153);
        MatteBorder bordeCelda11=BorderFactory.createMatteBorder(0, 0, 3, 3, colorBorde);
        MatteBorder bordeCelda12=BorderFactory.createMatteBorder(0, 3, 3, 3, colorBorde);
        MatteBorder bordeCelda13=BorderFactory.createMatteBorder(0, 3, 3, 0, colorBorde);
        MatteBorder bordeCelda21=BorderFactory.createMatteBorder(3, 0, 3, 3, colorBorde);
        MatteBorder bordeCelda22=BorderFactory.createMatteBorder(3, 3, 3, 3, colorBorde);
        MatteBorder bordeCelda23=BorderFactory.createMatteBorder(3, 3, 3, 0, colorBorde);
        MatteBorder bordeCelda31=BorderFactory.createMatteBorder(3, 0, 0, 3, colorBorde);
        MatteBorder bordeCelda32=BorderFactory.createMatteBorder(3, 3, 0, 3, colorBorde);
        MatteBorder bordeCelda33=BorderFactory.createMatteBorder(3, 3, 0, 0, colorBorde);
                
        Celda11.setBorder(bordeCelda11);
        Celda12.setBorder(bordeCelda12);
        Celda13.setBorder(bordeCelda13);
        Celda21.setBorder(bordeCelda21);
        Celda22.setBorder(bordeCelda22);
        Celda23.setBorder(bordeCelda23);
        Celda31.setBorder(bordeCelda31);
        Celda32.setBorder(bordeCelda32);
        Celda33.setBorder(bordeCelda33);
        
        // Array de Juego
        arrayJuego=new int[3][3];
        icono=new ImageIcon(getClass().getResource("/tresenraya/images/x.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        GridCeldas = new javax.swing.JPanel();
        Celda11 = new javax.swing.JPanel();
        jLabelCelda11 = new javax.swing.JLabel();
        Celda12 = new javax.swing.JPanel();
        jLabelCelda12 = new javax.swing.JLabel();
        Celda13 = new javax.swing.JPanel();
        jLabelCelda13 = new javax.swing.JLabel();
        Celda21 = new javax.swing.JPanel();
        jLabelCelda21 = new javax.swing.JLabel();
        Celda22 = new javax.swing.JPanel();
        jLabelCelda22 = new javax.swing.JLabel();
        Celda23 = new javax.swing.JPanel();
        jLabelCelda23 = new javax.swing.JLabel();
        Celda31 = new javax.swing.JPanel();
        jLabelCelda31 = new javax.swing.JLabel();
        Celda32 = new javax.swing.JPanel();
        jLabelCelda32 = new javax.swing.JLabel();
        Celda33 = new javax.swing.JPanel();
        TextoResultado = new javax.swing.JLabel();
        BotonReset = new javax.swing.JPanel();
        LabelReset = new javax.swing.JLabel();
        jLabelCelda33 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(335, 335));

        GridCeldas.setBackground(new java.awt.Color(204, 204, 204));
        GridCeldas.setOpaque(false);
        GridCeldas.setPreferredSize(new java.awt.Dimension(320, 320));
        GridCeldas.setLayout(new java.awt.GridLayout(3, 3));

        Celda11.setBackground(new java.awt.Color(255, 255, 255));
        Celda11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Celda11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Celda11MouseClicked(evt);
            }
        });

        jLabelCelda11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCelda11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCelda11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Celda11Layout = new javax.swing.GroupLayout(Celda11);
        Celda11.setLayout(Celda11Layout);
        Celda11Layout.setHorizontalGroup(
            Celda11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCelda11, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );
        Celda11Layout.setVerticalGroup(
            Celda11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCelda11, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );

        GridCeldas.add(Celda11);

        Celda12.setBackground(new java.awt.Color(255, 255, 255));
        Celda12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Celda12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Celda12MouseClicked(evt);
            }
        });

        jLabelCelda12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout Celda12Layout = new javax.swing.GroupLayout(Celda12);
        Celda12.setLayout(Celda12Layout);
        Celda12Layout.setHorizontalGroup(
            Celda12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCelda12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );
        Celda12Layout.setVerticalGroup(
            Celda12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCelda12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );

        GridCeldas.add(Celda12);

        Celda13.setBackground(new java.awt.Color(255, 255, 255));
        Celda13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Celda13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Celda13MouseClicked(evt);
            }
        });

        jLabelCelda13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout Celda13Layout = new javax.swing.GroupLayout(Celda13);
        Celda13.setLayout(Celda13Layout);
        Celda13Layout.setHorizontalGroup(
            Celda13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCelda13, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );
        Celda13Layout.setVerticalGroup(
            Celda13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCelda13, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );

        GridCeldas.add(Celda13);

        Celda21.setBackground(new java.awt.Color(255, 255, 255));
        Celda21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Celda21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Celda21MouseClicked(evt);
            }
        });

        jLabelCelda21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout Celda21Layout = new javax.swing.GroupLayout(Celda21);
        Celda21.setLayout(Celda21Layout);
        Celda21Layout.setHorizontalGroup(
            Celda21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCelda21, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );
        Celda21Layout.setVerticalGroup(
            Celda21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCelda21, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );

        GridCeldas.add(Celda21);

        Celda22.setBackground(new java.awt.Color(255, 255, 255));
        Celda22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Celda22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Celda22MouseClicked(evt);
            }
        });

        jLabelCelda22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout Celda22Layout = new javax.swing.GroupLayout(Celda22);
        Celda22.setLayout(Celda22Layout);
        Celda22Layout.setHorizontalGroup(
            Celda22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCelda22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Celda22Layout.setVerticalGroup(
            Celda22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCelda22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        GridCeldas.add(Celda22);

        Celda23.setBackground(new java.awt.Color(255, 255, 255));
        Celda23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Celda23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Celda23MouseClicked(evt);
            }
        });

        jLabelCelda23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout Celda23Layout = new javax.swing.GroupLayout(Celda23);
        Celda23.setLayout(Celda23Layout);
        Celda23Layout.setHorizontalGroup(
            Celda23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCelda23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );
        Celda23Layout.setVerticalGroup(
            Celda23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCelda23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );

        GridCeldas.add(Celda23);

        Celda31.setBackground(new java.awt.Color(255, 255, 255));
        Celda31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Celda31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Celda31MouseClicked(evt);
            }
        });

        jLabelCelda31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout Celda31Layout = new javax.swing.GroupLayout(Celda31);
        Celda31.setLayout(Celda31Layout);
        Celda31Layout.setHorizontalGroup(
            Celda31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCelda31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );
        Celda31Layout.setVerticalGroup(
            Celda31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCelda31, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );

        GridCeldas.add(Celda31);

        Celda32.setBackground(new java.awt.Color(255, 255, 255));
        Celda32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Celda32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Celda32MouseClicked(evt);
            }
        });

        jLabelCelda32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout Celda32Layout = new javax.swing.GroupLayout(Celda32);
        Celda32.setLayout(Celda32Layout);
        Celda32Layout.setHorizontalGroup(
            Celda32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCelda32, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );
        Celda32Layout.setVerticalGroup(
            Celda32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCelda32, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );

        GridCeldas.add(Celda32);

        Celda33.setBackground(new java.awt.Color(255, 255, 255));
        Celda33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Celda33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Celda33MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Celda33Layout = new javax.swing.GroupLayout(Celda33);
        Celda33.setLayout(Celda33Layout);
        Celda33Layout.setHorizontalGroup(
            Celda33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );
        Celda33Layout.setVerticalGroup(
            Celda33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );

        GridCeldas.add(Celda33);

        TextoResultado.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        TextoResultado.setForeground(new java.awt.Color(153, 153, 153));
        TextoResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        BotonReset.setBackground(new java.awt.Color(153, 153, 153));

        LabelReset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tresenraya/images/reset.png"))); // NOI18N
        LabelReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelResetMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BotonResetLayout = new javax.swing.GroupLayout(BotonReset);
        BotonReset.setLayout(BotonResetLayout);
        BotonResetLayout.setHorizontalGroup(
            BotonResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelReset, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
        );
        BotonResetLayout.setVerticalGroup(
            BotonResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelReset, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        jLabelCelda33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(GridCeldas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(TextoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(BotonReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabelCelda33, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(TextoResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GridCeldas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(BotonReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCelda33, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leerArray() {
        for(int i=0; i<3; i++) {
            for(int j=0; j<3; j++) {
                System.out.print(arrayJuego[i][j]+" ");
            }
            System.out.println("");
        }
        System.out.println("");
    }
    
    // EVENTO PARA CADA CASILLA. AL PULSAR, SE CAMBIA EL ARRAY
    private void Celda11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Celda11MouseClicked
        if(arrayJuego[0][0] == 0) {
            arrayJuego[0][0]=1;
            jLabelCelda11.setIcon(icono);
        }
        
        leerArray();        
    }//GEN-LAST:event_Celda11MouseClicked

    private void Celda12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Celda12MouseClicked
        if(arrayJuego[0][1] == 0) {
            arrayJuego[0][1]=1;
        }
        
        leerArray();   
    }//GEN-LAST:event_Celda12MouseClicked

    private void Celda13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Celda13MouseClicked
        if(arrayJuego[0][2] == 0) {
            arrayJuego[0][2]=1;
        }
        
        leerArray();   
    }//GEN-LAST:event_Celda13MouseClicked

    private void Celda21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Celda21MouseClicked
        if(arrayJuego[1][0] == 0) {
            arrayJuego[1][0]=1;
        }
        
        leerArray();   
    }//GEN-LAST:event_Celda21MouseClicked

    private void Celda22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Celda22MouseClicked
        if(arrayJuego[1][1] == 0) {
            arrayJuego[1][1]=1;
        }
        
        leerArray();   
    }//GEN-LAST:event_Celda22MouseClicked

    private void Celda23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Celda23MouseClicked
        if(arrayJuego[1][2] == 0) {
            arrayJuego[1][2]=1;
        }
        
        leerArray();   
    }//GEN-LAST:event_Celda23MouseClicked

    private void Celda31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Celda31MouseClicked
        if(arrayJuego[2][0] == 0) {
            arrayJuego[2][0]=1;
        }
        
        leerArray();   
    }//GEN-LAST:event_Celda31MouseClicked

    // BOTÓN RESETEAR JUEGO
    private void LabelResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelResetMouseClicked
        // Resetear Array
        for(int i=0; i<3; i++) {
            for(int j=0; j<3; j++) {
                arrayJuego[i][j]=0;
            }
        }
        
        // Eliminar iconos
        for(int i=0; i<9; i++) {
            
        }
    }//GEN-LAST:event_LabelResetMouseClicked

    private void Celda32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Celda32MouseClicked
        if(arrayJuego[2][1] == 0) {
            arrayJuego[2][1]=1;
        }

        leerArray();
    }//GEN-LAST:event_Celda32MouseClicked

    private void Celda33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Celda33MouseClicked
        if(arrayJuego[2][2] == 0) {
            arrayJuego[2][2]=1;
        }

        leerArray();
    }//GEN-LAST:event_Celda33MouseClicked

    private void jLabelCelda11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCelda11MouseClicked
        if(arrayJuego[0][0] == 0) {
            arrayJuego[0][0]=1;
            jLabelCelda11.setIcon(icono);
        }
        
        leerArray();  
    }//GEN-LAST:event_jLabelCelda11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoTresEnRaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoTresEnRaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoTresEnRaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoTresEnRaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoTresEnRaya().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonReset;
    private javax.swing.JPanel Celda11;
    private javax.swing.JPanel Celda12;
    private javax.swing.JPanel Celda13;
    private javax.swing.JPanel Celda21;
    private javax.swing.JPanel Celda22;
    private javax.swing.JPanel Celda23;
    private javax.swing.JPanel Celda31;
    private javax.swing.JPanel Celda32;
    private javax.swing.JPanel Celda33;
    private javax.swing.JPanel GridCeldas;
    private javax.swing.JLabel LabelReset;
    private javax.swing.JLabel TextoResultado;
    private javax.swing.JLabel jLabelCelda11;
    private javax.swing.JLabel jLabelCelda12;
    private javax.swing.JLabel jLabelCelda13;
    private javax.swing.JLabel jLabelCelda21;
    private javax.swing.JLabel jLabelCelda22;
    private javax.swing.JLabel jLabelCelda23;
    private javax.swing.JLabel jLabelCelda31;
    private javax.swing.JLabel jLabelCelda32;
    private javax.swing.JLabel jLabelCelda33;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
