SET SERVEROUTPUT ON
SET VERIFY OFF

-- Crear un cursor para ver todos los clientes que no hayan hecho pagos. Hazlo con un loop.
DECLARE
    CURSOR C1 IS
        SELECT NOMBRECLIENTE FROM CLIENTES C WHERE NOT EXISTS
            (SELECT CODIGOCLIENTE FROM PAGOS WHERE CODIGOCLIENTE=C.CODIGOCLIENTE);
            
    REGCLIENTE C1%ROWTYPE;
BEGIN
    OPEN C1;
    LOOP
        FETCH C1 INTO REGCLIENTE;
        EXIT WHEN C1%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('NOMBRE: '||REGCLIENTE.NOMBRECLIENTE);
    END LOOP;
    CLOSE C1;
END;