package Clases;
// Generated 11 dic 2024, 18:37:19 by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos implements java.io.Serializable {

	private int codDepar;
	private String nombreDepar;
	private Integer numAsig;
	private Set asignaturases = new HashSet(0);

	public Departamentos() {
	}

	public Departamentos(int codDepar) {
		this.codDepar = codDepar;
	}

	public Departamentos(int codDepar, String nombreDepar, Integer numAsig, Set asignaturases) {
		this.codDepar = codDepar;
		this.nombreDepar = nombreDepar;
		this.numAsig = numAsig;
		this.asignaturases = asignaturases;
	}

	public int getCodDepar() {
		return this.codDepar;
	}

	public void setCodDepar(int codDepar) {
		this.codDepar = codDepar;
	}

	public String getNombreDepar() {
		return this.nombreDepar;
	}

	public void setNombreDepar(String nombreDepar) {
		this.nombreDepar = nombreDepar;
	}

	public Integer getNumAsig() {
		return this.numAsig;
	}

	public void setNumAsig(Integer numAsig) {
		this.numAsig = numAsig;
	}

	public Set getAsignaturases() {
		return this.asignaturases;
	}

	public void setAsignaturases(Set asignaturases) {
		this.asignaturases = asignaturases;
	}

}
