package Clases;
// Generated 11 dic 2024, 18:37:19 by Hibernate Tools 5.4.33.Final

/**
 * EvaluacionesId generated by hbm2java
 */
public class EvaluacionesId implements java.io.Serializable {

	private int codEvaluacion;
	private int numAlumno;
	private int codAsig;

	public EvaluacionesId() {
	}

	public EvaluacionesId(int codEvaluacion, int numAlumno, int codAsig) {
		this.codEvaluacion = codEvaluacion;
		this.numAlumno = numAlumno;
		this.codAsig = codAsig;
	}

	public int getCodEvaluacion() {
		return this.codEvaluacion;
	}

	public void setCodEvaluacion(int codEvaluacion) {
		this.codEvaluacion = codEvaluacion;
	}

	public int getNumAlumno() {
		return this.numAlumno;
	}

	public void setNumAlumno(int numAlumno) {
		this.numAlumno = numAlumno;
	}

	public int getCodAsig() {
		return this.codAsig;
	}

	public void setCodAsig(int codAsig) {
		this.codAsig = codAsig;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EvaluacionesId))
			return false;
		EvaluacionesId castOther = (EvaluacionesId) other;

		return (this.getCodEvaluacion() == castOther.getCodEvaluacion())
				&& (this.getNumAlumno() == castOther.getNumAlumno()) && (this.getCodAsig() == castOther.getCodAsig());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodEvaluacion();
		result = 37 * result + this.getNumAlumno();
		result = 37 * result + this.getCodAsig();
		return result;
	}

}
