-- ***TABLA ALUMNOS***************

Drop table ALUMNOS;

create table ALUMNOS(
DNI	VARCHAR2(10) NOT NULL,
NOMBRE	VARCHAR2(15) NOT NULL,
APELLIDOS	VARCHAR2(20) NOT NULL,
FECHA_NAC	DATE,
DIRECCION	VARCHAR2(35),
POBLACION	VARCHAR2(20),
PROVINCIA	VARCHAR2(20),
CURSO	NUMBER(2)  NOT NULL,
NIVEL	VARCHAR2(10)  NOT NULL,
CLASE	CHAR(1)  NOT NULL,
FALTAS1	NUMBER(2),
FALTAS2	NUMBER(2),
FALTAS3	NUMBER(2)
);

INSERT INTO ALUMNOS VALUES ('34448974N', 'CONCHA', 'ESTRUCH VIDAL',TO_DATE('10/11/2003'),
'C/ MEDICO FELIX, 12','FUENSALIDA', 'TOLEDO',2,'CFGM','A',10,8,7);

INSERT INTO ALUMNOS VALUES ('34448999N', 'DORA', 'BREÑA MARTIN',TO_DATE('10/12/2001'),
'C/ GRANADA 20','TALAVERA', 'TOLEDO',1,'ESO','B',0,0,0);

INSERT INTO ALUMNOS VALUES ('14228974N', 'MARIA', 'GRACIA GIL',TO_DATE('07/10/2008'),
'C/ LOS ALFARES 20','OROPESA', 'TOLEDO',2,'CFGM','A',9,6,0);

INSERT INTO ALUMNOS VALUES ('23400999B', 'ANTONIO', 'RAMIREZ MARTIN',TO_DATE('01/08/2008'),
'C/ GENERAL AGUIRRE 10','NAVALMORAL', 'CACERES',1,'ESO','B',2,1,2);

INSERT INTO ALUMNOS VALUES ('8900894A', 'ALICIA', 'GOMEZ GONZALEZ',TO_DATE('06/11/2008'),
'C/ CAMINO EL RIO 12','SAN FERNANDO', 'MADRID',2,'CFGM','A',6,0,10);

INSERT INTO ALUMNOS VALUES ('2348019B', 'JUAN', 'ALFAR SALA',TO_DATE('13/12/2001'),
'C/ LAS HOJAS 110','FUENSALIDA', 'TOLEDO',1,'CFGS','C',10,4,10);

INSERT INTO ALUMNOS VALUES ('2148009C', 'PEDRO JUAN', 'MARTIN MARTIN',TO_DATE('04/07/2005'),
'C/ SEGOVIA 24-2A','ALCORCON', 'MADRID',1,'CFGS','C',0,0,4);

INSERT INTO ALUMNOS VALUES ('1330074A', 'MARIO', 'GARCÍA GIL',TO_DATE('07/09/1998'),
'C/ LOS MAMELUCOS 22','TALAVERA', 'TOLEDO',2,'CFGS','C',0,1,0);

INSERT INTO ALUMNOS VALUES ('6800704A', 'BARBARA', 'FLORES SANZ',TO_DATE('07/09/1998'),
'C/ ALAMEDA 11','TALAVERA', 'TOLEDO',2,'CFGM','A',1,1,0);

INSERT INTO ALUMNOS VALUES ('59440025Z', 'BLANCA', 'GALA SOPENA',TO_DATE('01/03/1998'),
'AV/ LAS CRUCES','LAGARTERA', 'TOLEDO',1,'CFGS','C',0,10,0);

INSERT INTO ALUMNOS VALUES ('19235987M', 'BLANCA', 'PEREZ LOPEZ',TO_DATE('07/12/2098'),
'C/ DE LOS CARMENES','TORRIJOS', 'TOLEDO',2,'CFGS','C',9,5,5);

INSERT INTO ALUMNOS VALUES ('36985211C', 'BLANCA', 'MARTIN SANCHEZ',TO_DATE('17/09/1998'),
'C/ LOS CIRUELOS 22','OROPESA', 'TOLEDO',2,'CFGS','C',3,1,0);
COMMIT;

-- ******** TABLA NOTAS_ALUMNOS: ***********

Drop table notas_alumnos cascade constraints;

create table NOTAS_ALUMNOS
 (
   NOMBRE_ALUMNO VARCHAR2(25) NOT NULL ,
   nota1 number(2),
   nota2 number(2),
   nota3 number(2)
 ) ;
 
insert into NOTAS_ALUMNOS VALUES ('Alcalde García, M. Luisa',5,5,5);
insert into NOTAS_ALUMNOS VALUES ('Benito Martín, Luis',7,6,8);
insert into NOTAS_ALUMNOS VALUES ('Casas Martínez, Manuel',5,10,0);
insert into NOTAS_ALUMNOS VALUES ('Corregidor Sánchez, Ana',10,10,4);
insert into NOTAS_ALUMNOS VALUES ('Díaz Sánchez, Maria',NULL,NULL,7);
COMMIT;

-- ******** TABLA LIBRERIAS: *************

Drop table LIBRERIAS cascade constraints;

create table LIBRERIAS
 (TEMA CHAR(15) NOT NULL ,
  ESTANTE CHAR(1),
  EJEMPLARES NUMBER(2)
 ) ;

INSERT INTO LIBRERIAS VALUES ('INFORMATICA', 'A',15);
INSERT INTO LIBRERIAS VALUES ('ECONOMIA',    'A',10);
INSERT INTO LIBRERIAS VALUES ('GEOMETRIA',    'B',8);
INSERT INTO LIBRERIAS VALUES ('FILOSOFIA',   'C',7);
INSERT INTO LIBRERIAS VALUES ('DIBUJO',      'C',10);
INSERT INTO LIBRERIAS VALUES ('MEDICINA',    'C',0);
INSERT INTO LIBRERIAS VALUES ('GEOGRAFIA',    'B',11);
INSERT INTO LIBRERIAS VALUES ('GEOLOGIA',    'B',7);
INSERT INTO LIBRERIAS VALUES ('SOCIEDAD',    'D',9);
INSERT INTO LIBRERIAS VALUES ('LABORES',     'B',20);
INSERT INTO LIBRERIAS VALUES ('JARDINERIA',    'E',0);
COMMIT;