--21
SELECT NOMBRE, APELLIDOS, DNI FROM ALUMNOS WHERE NOMBRE='BLANCA';
SELECT NOMBRE, APELLIDOS, DNI FROM ALUMNOS WHERE NOMBRE LIKE 'BLAN%' ORDER BY APELLIDOS DESC;

--22
SELECT nombre,apellidos,direccion,fecha_nac AS FECHA_DE_NACIMIENTO FROM ALUMNOS WHERE fecha_nac='07/09/1998' ORDER BY nombre,apellidos,direccion,fecha_nac;

--23
SELECT NOMBRE, APELLIDOS, FECHA_NAC FROM ALUMNOS WHERE FECHA_NAC BETWEEN '01/01/1998' AND '31/12/1998' ORDER BY FECHA_NAC DESC;

--24
SELECT NOMBRE, POBLACION FROM ALUMNOS WHERE POBLACION='TALAVERA' OR POBLACION='OROPESA' ORDER BY nombre ASC;

--25
SELECT * FROM ALUMNOS WHERE POBLACION!='TALAVERA' AND POBLACION!='OROPESA';

--26
SELECT NOMBRE, APELLIDOS, POBLACION FROM ALUMNOS WHERE POBLACION!='TORRIJOS' ORDER BY NOMBRE,POBLACION;

--27
SELECT * FROM LIBRERIAS WHERE TEMA LIKE 'GEO%';

--28
SELECT NOMBRE AS "ALUMNOS DE TOLEDO" FROM ALUMNOS WHERE PROVINCIA LIKE 'TOLEDO';

--29
SELECT DNI AS "DNI ALUMNOS DE MADRID" FROM ALUMNOS WHERE PROVINCIA='MADRID';

--30
SELECT  NOMBRE, APELLIDOS, NIVEL FROM ALUMNOS WHERE NIVEL='CFGM' OR NIVEL='CFGS';

--31
SELECT NOMBRE_ALUMNO, NOTA1+NOTA2+NOTA3 AS "SUMA DE NOTAS" FROM NOTAS_ALUMNOS WHERE (NOTA1+NOTA2+NOTA3)/3>=5;

--32
SELECT NOMBRE, APELLIDOS, DIRECCION FROM ALUMNOS WHERE DIRECCION NOT LIKE 'AV/%' ORDER BY DIRECCION, APELLIDOS;

--33
SELECT TEMA AS "TEMA SIN EJEMPLARES" FROM LIBRERIAS WHERE EJEMPLARES=0;

--34
SELECT TEMA, ESTANTE FROM LIBRERIAS WHERE ESTANTE='A' OR ESTANTE='D';

--35
SELECT TEMA,EJEMPLARES FROM LIBRERIAS WHERE TEMA='DIBUJO' OR TEMA='MEDICINA' OR TEMA='LABORES' OR TEMA='INFORMATICA' OR TEMA='GEOGRAFIA';

--36
SELECT APELLIDOS FROM ALUMNOS WHERE APELLIDOS LIKE 'G%' ORDER BY APELLIDOS ASC;

--37
SELECT NOMBRE_ALUMNO, NOTA1*1.1,NOTA2*1.1,NOTA3*1.1 FROM NOTAS_ALUMNOS WHERE (NOTA1+NOTA2+NOTA3)/3<6 ORDER BY 2,3,4;

--38
SELECT NOMBRE, FALTAS1, FALTAS2, FALTAS3 FROM ALUMNOS WHERE FALTAS3>(FALTAS2-FALTAS1);

--39
SELECT NOMBRE, FALTAS1*FALTAS2 AS SALIDA1, FALTAS2*FALTAS3 AS SALIDA2 FROM ALUMNOS WHERE (FALTAS1*FALTAS2)=(FALTAS2*FALTAS3);

--40
SELECT CONCAT(APELLIDOS, NOMBRE) AS "NOMBRE COMPLETO", POBLACION FROM ALUMNOS WHERE POBLACION='TALAVERA' ORDER BY APELLIDOS ASC;

--41
SELECT UPPER(NOMBRE), CURSO, LOWER(NIVEL) FROM ALUMNOS WHERE CURSO=2 ORDER BY NIVEL DESC;

--42
SELECT NOMBRE, INITCAP(POBLACION), LOWER(PROVINCIA) FROM ALUMNOS WHERE NOMBRE LIKE '% %';

--43 
--NO SE HACERLO

--44
SELECT SUBSTR(APELLIDOS || '....................',1,20) || ', ' || NOMBRE AS "NOMBRE COMPLETO" FROM ALUMNOS;

--45
SELECT TEMA FROM LIBRERIAS WHERE TEMA LIKE 'GEO%ia' AND EJEMPLARES BETWEEN 5 AND 20;

--46
SELECT TEMA FROM LIBRERIAS WHERE UPPER(TRIM(TEMA)) LIKE 'GEO%' AND LOWER (TRIM(TEMA)) LIKE '%ia' AND EJEMPLARES BETWEEN 5 AND 20;

--47
SELECT TEMA, COUNT(*) AS "TOTAL" FROM LIBRERIAS WHERE TEMA LIKE 'GEO%ia' AND EJEMPLARES BETWEEN 5 AND 20;

--48
SELECT NOMBRE, DIRECCION, PROVINCIA FROM ALUMNOS WHERE PROVINCIA='TOLEDO' AND DIRECCION!='%20';

--49
SELECT 
    ROUND(AVG(FALTAS1), 2) AS "MEDIA FALTAS 1ª EVALUACIÓN",
    SUM(FALTAS2) AS "SUMA FALTAS SEGUNDA EVALUACION",
    COUNT(*) AS "TOTAL ALUMNOS"
FROM ALUMNOS;

--52
SELECT TRUNC(SUM(FALTAS3)/COUNT(*),2) "FALTAS" FROM ALUMNOS;

--54
SELECT INITCAP(NOMBRE), INITCAP(APELLIDOS), UPPER(DIRECCION), UPPER(PROVINCIA), CONCAT(CURSO, CONCAT('º',LOWER(CLASE))) "GRUPO" FROM ALUMNOS;

--60
SELECT TO_CHAR(SYSDATE, 'DD MM YYYY') FROM DUAL;
SELECT TO_CHAR(SYSDATE, DAY, 'DD/MM/YYYY') FROM DUAL;

--63
SELECT NOMBRE, APELLIDOS, FECHA_NAC, TO_CHAR(FECHA_NAC, 'MONTH') "MES DE NACIMIENTO", TO_CHAR(FECHA_NAC, 'DAY') "DIA DE NACIMEINTO" FROM ALUMNOS ORDER BY FECHA_NAC;