SET SERVEROUTPUT ON
SET VERIFY OFF


-- MOSTRAR EL NOMBRE DE UN CLIENTE DADO SU CÓDIGO
DECLARE
    CODIGO CLIENTES.CODIGOCLIENTE%TYPE:='&codigo';
    NOMBRE CLIENTES.NOMBRECLIENTE%TYPE;
BEGIN
    -- Seleccionamos el nombre y lo metemos dentro de la variable anteriormente creada
    SELECT NOMBRECLIENTE INTO NOMBRE
        FROM CLIENTES 
        WHERE CODIGOCLIENTE=CODIGO;
    
    DBMS_OUTPUT.PUT_LINE(NOMBRE);
    
    EXCEPTION
        -- Excepción por si no existe el cliente con ese código
        WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('No encontrado');
END;
/


-- MOSTRAR EL PRECIOVENTA Y LA GAMA DE UN PRODUCTO DADO SU CÓDIGO
DECLARE 
    P_GAMA PRODUCTOS.GAMA%TYPE;
    P_VENTA PRODUCTOS.PRECIOVENTA%TYPE;
    CODIGO PRODUCTOS.CODIGOPRODUCTO%TYPE:='&codigo';
BEGIN
    SELECT GAMA, PRECIOVENTA INTO P_GAMA, P_VENTA
        FROM PRODUCTOS WHERE CODIGOPRODUCTO=CODIGO;
    DBMS_OUTPUT.PUT_LINE('PRECIO: '||P_VENTA);
    DBMS_OUTPUT.PUT_LINE('GAMA: ' || P_GAMA);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Datos no encontrados');
END;
/


-- MOSTRAR TODA LA INFORMACIÓN DE UN PEDIDO DADO UN CÓDIGO
-- (FECHA ESPERADA, FECHA ENTREGA, FECHA PEDIDO, ESTADO, COMENTARIOS)
DECLARE
    CODIGO NUMBER(10):='&codigo';
    -- Con ROWTYPE, cogemos toda la fila directamente, y luego de esa podemos seleccionar el dato que necesitemos
    V_PEDIDO PEDIDOS%ROWTYPE;
BEGIN
    SELECT * INTO V_PEDIDO
    FROM PEDIDOS WHERE CODIGO=CODIGOPEDIDO;
    DBMS_OUTPUT.PUT_LINE('FECHA PEDIDO: '|| V_PEDIDO.FECHAPEDIDO);
    DBMS_OUTPUT.PUT_LINE('FECHA ESPERADA: '|| V_PEDIDO.FECHAESPERADA);
    DBMS_OUTPUT.PUT_LINE('FECHA ENTREGA: '|| V_PEDIDO.FECHAENTREGA);
    DBMS_OUTPUT.PUT_LINE('ESTADO: '|| V_PEDIDO.ESTADO);
    DBMS_OUTPUT.PUT_LINE('COMENTARIOS: '|| V_PEDIDO.COMENTARIOS);
END;
/