SET SERVEROUTPUT ON
SET VERIFY OFF

-- Crear un cursor para ver todos los productos pedidos en un pedido. Muestra la cantidad tambien.
CREATE OR REPLACE TRIGGER ACTUALIZAR_LIBROS
AFTER UPDATE OF PRECIO
ON LIBROS
FOR EACH ROW
BEGIN

    INSERT INTO CONTROL VALUES (USER, SYSDATE, PRECIO, :NEW.PRECIO);
END;