-- EXAMEN
-- EJERCICIO 1
SELECT DNI, NOMBRE || ' ' || APELLIDO "NOMBRE COMPLETO", PROFESION 
    FROM EMPLEADOS
        WHERE IDCAMERINO IN
           (SELECT IDCAMERINO FROM CAMERINOS); 

-- EJERCICIO 2
SELECT PROFESION, COUNT(PROFESION) "NUMERO EMPLEADOS"
        FROM EMPLEADOS
    GROUP BY PROFESION
        ORDER BY COUNT(PROFESION) ASC;
    
-- EJERCICIO 3
SELECT DNI, NOMBRE || ' ' || APELLIDO "NOMBRE COMPLETO" 
        FROM EMPLEADOS
    WHERE IDEMPLEADO NOT IN
        (SELECT IDARTISTA FROM ART_REALIZAN_NUMERO_FUNCION);
    
-- EJERCICIO 4
SELECT DISTINCT E.NOMBREELEMENTO "NOMBRE ELEMENTO"
    FROM ELEMENTOS E JOIN ELEMENTOS_USADOS_EN_NUMEROS X ON X.IDELEMENTO=E.IDELEMENTO
                     JOIN NUMEROS N ON N.IDNUMERO=X.IDNUMERO
        WHERE N.TIPO LIKE 'Malabarismo%';

-- EJERCICIO 5
SELECT DISTINCT A.DNI, A.NOMBRE, A.APELLIDO, N.TITULO
    FROM EMPLEADOS A JOIN ART_REALIZAN_NUMERO_FUNCION X ON X.IDARTISTA=A.IDEMPLEADO
                     JOIN NUMEROS N ON X.IDNUMERO=N.IDNUMERO
                     JOIN FUNCIONES F ON X.IDFUNCION=F.IDFUNCION
                     JOIN CIUDADES C ON C.IDCIUDAD=F.IDCIUDAD
        WHERE C.NOMBRECIUDAD='Barcelona' AND F.IDFUNCION=1
            ORDER BY N.TITULO;

-- EJERCICIO 6
SELECT DISTINCT E.NOMBREELEMENTO "NOMBRE ELEMENTO", A.NOMBRE || ' ' || A.APELLIDO "NOMBRE COMPLETO"
    FROM ELEMENTOS E JOIN EMPLEADOS A ON A.IDEMPLEADO=E.IDEMPLEADO
                     JOIN ELEMENTOS_USADOS_EN_NUMEROS X ON X.IDELEMENTO=E.IDELEMENTO
                     JOIN NUMEROS N ON X.IDNUMERO=N.IDNUMERO
                     JOIN ART_REALIZAN_NUMERO_FUNCION AR ON AR.IDNUMERO=N.IDNUMERO
                     JOIN FUNCIONES F ON AR.IDFUNCION=F.IDFUNCION
                     JOIN CIUDADES C ON C.IDCIUDAD=F.IDCIUDAD
                WHERE C.IDCIUDAD=1 AND F.IDFUNCION=2
                ORDER BY A.NOMBRE || ' ' || A.APELLIDO;            

-- EJERCICIO 7
SELECT N.TITULO "NUMERO", 
    CASE 
        WHEN AVG(X.PUNTUACION) IS NULL THEN -1
        ELSE ROUND(AVG(X.PUNTUACION),2) 
            END "VALORACIÓN MEDIA DEL NÚMERO"
    FROM NUMEROS N LEFT JOIN ART_REALIZAN_NUMERO_FUNCION X ON X.IDNUMERO=N.IDNUMERO
        GROUP BY N.TITULO
        ORDER BY AVG(X.PUNTUACION) DESC;

-- EJERCICIO 8
SELECT E.NOMBRE, E.APELLIDO, E.PROFESION, 
        CASE 
            WHEN AVG(X.PUNTUACION) IS NULL THEN -1
            ELSE ROUND(AVG(X.PUNTUACION),2) 
            END "VALORACIÓN MEDIA DEL ARTISTA"
        FROM EMPLEADOS E LEFT JOIN ART_REALIZAN_NUMERO_FUNCION X ON X.IDARTISTA=E.IDEMPLEADO
    GROUP BY E.NOMBRE, E.APELLIDO, E.PROFESION
    ORDER BY AVG(X.PUNTUACION) DESC;

            
-- EJERCICIO 9
SELECT SUM(PVP_MONTAJE) "SUMA PLUS MONTAJE"
        FROM ELEMENTOS E JOIN ELEMENTOS_USADOS_EN_NUMEROS X ON X.IDELEMENTO=E.IDELEMENTO
                          JOIN NUMEROS N ON X.IDNUMERO=N.IDNUMERO
                          JOIN ART_REALIZAN_NUMERO_FUNCION AR ON AR.IDNUMERO=N.IDNUMERO
                          JOIN FUNCIONES F ON F.IDFUNCION=AR.IDFUNCION
                          JOIN CIUDADES C ON F.IDCIUDAD=C.IDCIUDAD
    WHERE C.IDCIUDAD=1 AND F.IDFUNCION=1;

-- EJERCICIO 10
SELECT DNI, NOMBRE || ' ' || APELLIDO "NOMBRE COMPLETO", PROFESION
        FROM EMPLEADOS
    WHERE IDCAMERINO=1;
    
-- EJERICIO 11
SELECT IDCAMERINO, COUNT(IDCAMERINO) "ARTISTAS ASIGNADOS"
    FROM CAMERINOS JOIN EMPLEADOS USING(IDCAMERINO)
        WHERE IDCAMERINO IN 
            (SELECT IDCAMERINO FROM EMPLEADOS
                GROUP BY IDCAMERINO
                HAVING COUNT(IDCAMERINO)=
                    (SELECT MAX(COUNT(IDCAMERINO))
                        FROM EMPLEADOS
                        GROUP BY IDCAMERINO))
        GROUP BY IDCAMERINO;