/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bingo.pantallas;

import java.awt.Color;
import java.awt.Label;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Alfonso
 */
public class JuegoBingo extends javax.swing.JFrame {

    private String[][] labels;
    private ArrayList<Integer> repetidos;
    private int contVictoria=0;
    /**
     * Creates new form JuegoBingo
     */
    public JuegoBingo() {
        initComponents();
        
        // Estilos del JFrame
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/bingo/images/logo.png")).getImage());
        
        // Inicializar el arraylist de números
        repetidos=new ArrayList<>();
        
        // Agrego los labels
        labels=new String[5][5];
        añadirCeldas(labels);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Boleto = new javax.swing.JPanel();
        GridLayoutBoleto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelNumeroGenerado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boleto.setBackground(new java.awt.Color(102, 153, 255));
        Boleto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        GridLayoutBoleto.setBackground(new java.awt.Color(255, 255, 255));
        GridLayoutBoleto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        GridLayoutBoleto.setLayout(new java.awt.GridLayout(5, 5));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BINGO");

        javax.swing.GroupLayout BoletoLayout = new javax.swing.GroupLayout(Boleto);
        Boleto.setLayout(BoletoLayout);
        BoletoLayout.setHorizontalGroup(
            BoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoletoLayout.createSequentialGroup()
                .addGroup(BoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BoletoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BoletoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(GridLayoutBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        BoletoLayout.setVerticalGroup(
            BoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoletoLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GridLayoutBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jPanel1.add(Boleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 39, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TIRAR");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 149, -1, -1));

        jLabelNumeroGenerado.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelNumeroGenerado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelNumeroGenerado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 90, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Al hacer click en el botón, se generan números aleatorios
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        int random=(int)(1+Math.random()*75);        
        
        // Evitar que se generen números repetidos
        while(repetidos.contains(random)) {
            random=(int)(1+Math.random()*75);            
        }
        repetidos.add(random);
        
        jLabelNumeroGenerado.setText(String.valueOf(random));
        
        verificarVictoria(random);        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void añadirCeldas(String[][] labels) {
        int cont=0;        
        int inicio=1;
        int numero=0;
        
        for(int i=0; i<5; i++) {
            for(int j=0; j<5; j++) {
                cont++;
                String nombre="label"+cont;
                labels[i][j]=nombre;                
                JLabel label=new JLabel();
                
                label.setName(nombre);
                label.setForeground(Color.BLACK);                
                label.setHorizontalAlignment(JLabel.CENTER);        
                // Negrita
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
                label.setOpaque(true); 
                
                // Fondo diferente para casillas pares e impares
                if(cont%2 == 0) {
                    label.setBackground(new Color(153,204,255));
                    label.setForeground(Color.WHITE);
                } else {
                    label.setBackground(Color.WHITE);
                    label.setForeground(Color.BLACK);
                }

                // Número del label
                numero=(int)(Math.random()*15)+inicio;
                // Evitamos que se repita
                while(noRepetido(numero, labels)) {
                    numero=(int)(Math.random()*15)+inicio;
                }                
                
                label.setText(String.valueOf(numero));
                
                GridLayoutBoleto.add(label);
            }
            inicio+=15;
        }
    }
    
    // Función para evitar que el número se repita en el tablero
    private boolean noRepetido(int num, String[][] labels) {
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                if (labels[i][j] != null && Integer.parseInt(labels[i][j].substring(5,labels[i][j].length())) == num) {
                    return true;
                }
            }
        }
        return false;
    }

    public void verificarVictoria(int random) {
        if(contVictoria < 25) {
            buscarNumero(labels, random);
            
        } else {
            contVictoria=0;
            
            // Abrir diálogo de Victoria
            Victoria v=new Victoria(this, true);
            v.setVisible(true);
            
            // Resetear boleto
            añadirCeldas(labels);
        }                       
    }
    
    // Función para buscar el número que ha salido con el random
    private void buscarNumero(String[][] labels, int numero) {                
        for(int i=0; i<5; i++) {
            for(int j=0; j<5; j++) {
                JLabel label = (JLabel) GridLayoutBoleto.getComponent(i * 5 + j);

                int numeroElegido=Integer.parseInt(String.valueOf(label.getText()));
                
                if(numero == numeroElegido) {                    
                    // Verificar que la casilla en cuestión no haya sido seleccionada antes, ya que de lo
                    // contrario, esto va a hacer que se sume el contador de victoria cuando salgan números
                    // repetidos
                    if(!label.getBackground().equals(new Color(184, 44, 44))) {
                        contVictoria++;
                        
                        label.setBackground(new Color(184, 44, 44));                   
                        label.setForeground(Color.WHITE);
                    }                    
                }
            }
        }
    }
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Boleto;
    private javax.swing.JPanel GridLayoutBoleto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelNumeroGenerado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
