package Clases;
// Generated 12 dic 2024, 19:22:02 by Hibernate Tools 5.4.33.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Alumnos generated by hbm2java
 */
public class Alumnos implements java.io.Serializable {

	private BigInteger codalum;
	private Alumnos alumnos;
	private Cursos cursos;
	private String nombre;
	private String direccion;
	private String poblacion;
	private String telef;
	private Set alumnoses = new HashSet(0);
	private Set matriculases = new HashSet(0);

	public Alumnos() {
	}

	public Alumnos(BigInteger codalum) {
		this.codalum = codalum;
	}

	public Alumnos(BigInteger codalum, Alumnos alumnos, Cursos cursos, String nombre, String direccion,
			String poblacion, String telef, Set alumnoses, Set matriculases) {
		this.codalum = codalum;
		this.alumnos = alumnos;
		this.cursos = cursos;
		this.nombre = nombre;
		this.direccion = direccion;
		this.poblacion = poblacion;
		this.telef = telef;
		this.alumnoses = alumnoses;
		this.matriculases = matriculases;
	}

	public BigInteger getCodalum() {
		return this.codalum;
	}

	public void setCodalum(BigInteger codalum) {
		this.codalum = codalum;
	}

	public Alumnos getAlumnos() {
		return this.alumnos;
	}

	public void setAlumnos(Alumnos alumnos) {
		this.alumnos = alumnos;
	}

	public Cursos getCursos() {
		return this.cursos;
	}

	public void setCursos(Cursos cursos) {
		this.cursos = cursos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	public String getTelef() {
		return this.telef;
	}

	public void setTelef(String telef) {
		this.telef = telef;
	}

	public Set getAlumnoses() {
		return this.alumnoses;
	}

	public void setAlumnoses(Set alumnoses) {
		this.alumnoses = alumnoses;
	}

	public Set getMatriculases() {
		return this.matriculases;
	}

	public void setMatriculases(Set matriculases) {
		this.matriculases = matriculases;
	}

}
