package Clases;
// Generated 12 dic 2024, 19:22:02 by Hibernate Tools 5.4.33.Final

import java.math.BigInteger;

/**
 * CursoasigId generated by hbm2java
 */
public class CursoasigId implements java.io.Serializable {

	private BigInteger codcurso;
	private BigInteger codasig;

	public CursoasigId() {
	}

	public CursoasigId(BigInteger codcurso, BigInteger codasig) {
		this.codcurso = codcurso;
		this.codasig = codasig;
	}

	public BigInteger getCodcurso() {
		return this.codcurso;
	}

	public void setCodcurso(BigInteger codcurso) {
		this.codcurso = codcurso;
	}

	public BigInteger getCodasig() {
		return this.codasig;
	}

	public void setCodasig(BigInteger codasig) {
		this.codasig = codasig;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CursoasigId))
			return false;
		CursoasigId castOther = (CursoasigId) other;

		return ((this.getCodcurso() == castOther.getCodcurso()) || (this.getCodcurso() != null
				&& castOther.getCodcurso() != null && this.getCodcurso().equals(castOther.getCodcurso())))
				&& ((this.getCodasig() == castOther.getCodasig()) || (this.getCodasig() != null
						&& castOther.getCodasig() != null && this.getCodasig().equals(castOther.getCodasig())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodcurso() == null ? 0 : this.getCodcurso().hashCode());
		result = 37 * result + (getCodasig() == null ? 0 : this.getCodasig().hashCode());
		return result;
	}

}
