package Clases;
// Generated 12 dic 2024, 19:22:02 by Hibernate Tools 5.4.33.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Cursos generated by hbm2java
 */
public class Cursos implements java.io.Serializable {

	private BigInteger codcurso;
	private String denominacion;
	private BigInteger precio;
	private String nivel;
	private Set alumnoses = new HashSet(0);
	private Set cursoasigs = new HashSet(0);

	public Cursos() {
	}

	public Cursos(BigInteger codcurso) {
		this.codcurso = codcurso;
	}

	public Cursos(BigInteger codcurso, String denominacion, BigInteger precio, String nivel, Set alumnoses,
			Set cursoasigs) {
		this.codcurso = codcurso;
		this.denominacion = denominacion;
		this.precio = precio;
		this.nivel = nivel;
		this.alumnoses = alumnoses;
		this.cursoasigs = cursoasigs;
	}

	public BigInteger getCodcurso() {
		return this.codcurso;
	}

	public void setCodcurso(BigInteger codcurso) {
		this.codcurso = codcurso;
	}

	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	public BigInteger getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigInteger precio) {
		this.precio = precio;
	}

	public String getNivel() {
		return this.nivel;
	}

	public void setNivel(String nivel) {
		this.nivel = nivel;
	}

	public Set getAlumnoses() {
		return this.alumnoses;
	}

	public void setAlumnoses(Set alumnoses) {
		this.alumnoses = alumnoses;
	}

	public Set getCursoasigs() {
		return this.cursoasigs;
	}

	public void setCursoasigs(Set cursoasigs) {
		this.cursoasigs = cursoasigs;
	}

}
