package Clases;
// Generated 12 dic 2024, 19:22:02 by Hibernate Tools 5.4.33.Final

import java.math.BigInteger;

/**
 * MatriculasId generated by hbm2java
 */
public class MatriculasId implements java.io.Serializable {

	private BigInteger codalum;
	private BigInteger codasig;

	public MatriculasId() {
	}

	public MatriculasId(BigInteger codalum, BigInteger codasig) {
		this.codalum = codalum;
		this.codasig = codasig;
	}

	public BigInteger getCodalum() {
		return this.codalum;
	}

	public void setCodalum(BigInteger codalum) {
		this.codalum = codalum;
	}

	public BigInteger getCodasig() {
		return this.codasig;
	}

	public void setCodasig(BigInteger codasig) {
		this.codasig = codasig;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MatriculasId))
			return false;
		MatriculasId castOther = (MatriculasId) other;

		return ((this.getCodalum() == castOther.getCodalum()) || (this.getCodalum() != null
				&& castOther.getCodalum() != null && this.getCodalum().equals(castOther.getCodalum())))
				&& ((this.getCodasig() == castOther.getCodasig()) || (this.getCodasig() != null
						&& castOther.getCodasig() != null && this.getCodasig().equals(castOther.getCodasig())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodalum() == null ? 0 : this.getCodalum().hashCode());
		result = 37 * result + (getCodasig() == null ? 0 : this.getCodasig().hashCode());
		return result;
	}

}
