package Clases;
// Generated 12 dic 2024, 19:22:02 by Hibernate Tools 5.4.33.Final

import java.math.BigInteger;
import java.util.Date;

/**
 * Matriculas generated by hbm2java
 */
public class Matriculas implements java.io.Serializable {

	private MatriculasId id;
	private Alumnos alumnos;
	private Asignaturas asignaturas;
	private Date fechamatr;
	private BigInteger notaasig;

	public Matriculas() {
	}

	public Matriculas(MatriculasId id, Alumnos alumnos, Asignaturas asignaturas) {
		this.id = id;
		this.alumnos = alumnos;
		this.asignaturas = asignaturas;
	}

	public Matriculas(MatriculasId id, Alumnos alumnos, Asignaturas asignaturas, Date fechamatr, BigInteger notaasig) {
		this.id = id;
		this.alumnos = alumnos;
		this.asignaturas = asignaturas;
		this.fechamatr = fechamatr;
		this.notaasig = notaasig;
	}

	public MatriculasId getId() {
		return this.id;
	}

	public void setId(MatriculasId id) {
		this.id = id;
	}

	public Alumnos getAlumnos() {
		return this.alumnos;
	}

	public void setAlumnos(Alumnos alumnos) {
		this.alumnos = alumnos;
	}

	public Asignaturas getAsignaturas() {
		return this.asignaturas;
	}

	public void setAsignaturas(Asignaturas asignaturas) {
		this.asignaturas = asignaturas;
	}

	public Date getFechamatr() {
		return this.fechamatr;
	}

	public void setFechamatr(Date fechamatr) {
		this.fechamatr = fechamatr;
	}

	public BigInteger getNotaasig() {
		return this.notaasig;
	}

	public void setNotaasig(BigInteger notaasig) {
		this.notaasig = notaasig;
	}

}
