package Clases;
// Generated 12 dic 2024, 19:22:02 by Hibernate Tools 5.4.33.Final

import java.math.BigInteger;

/**
 * NuevosalumnosId generated by hbm2java
 */
public class NuevosalumnosId implements java.io.Serializable {

	private BigInteger codalum;
	private String nombre;
	private String direccion;
	private String poblacion;
	private String telef;

	public NuevosalumnosId() {
	}

	public NuevosalumnosId(BigInteger codalum) {
		this.codalum = codalum;
	}

	public NuevosalumnosId(BigInteger codalum, String nombre, String direccion, String poblacion, String telef) {
		this.codalum = codalum;
		this.nombre = nombre;
		this.direccion = direccion;
		this.poblacion = poblacion;
		this.telef = telef;
	}

	public BigInteger getCodalum() {
		return this.codalum;
	}

	public void setCodalum(BigInteger codalum) {
		this.codalum = codalum;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	public String getTelef() {
		return this.telef;
	}

	public void setTelef(String telef) {
		this.telef = telef;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NuevosalumnosId))
			return false;
		NuevosalumnosId castOther = (NuevosalumnosId) other;

		return ((this.getCodalum() == castOther.getCodalum()) || (this.getCodalum() != null
				&& castOther.getCodalum() != null && this.getCodalum().equals(castOther.getCodalum())))
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& ((this.getDireccion() == castOther.getDireccion()) || (this.getDireccion() != null
						&& castOther.getDireccion() != null && this.getDireccion().equals(castOther.getDireccion())))
				&& ((this.getPoblacion() == castOther.getPoblacion()) || (this.getPoblacion() != null
						&& castOther.getPoblacion() != null && this.getPoblacion().equals(castOther.getPoblacion())))
				&& ((this.getTelef() == castOther.getTelef()) || (this.getTelef() != null
						&& castOther.getTelef() != null && this.getTelef().equals(castOther.getTelef())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodalum() == null ? 0 : this.getCodalum().hashCode());
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getDireccion() == null ? 0 : this.getDireccion().hashCode());
		result = 37 * result + (getPoblacion() == null ? 0 : this.getPoblacion().hashCode());
		result = 37 * result + (getTelef() == null ? 0 : this.getTelef().hashCode());
		return result;
	}

}
