-- EJERCICIO 1
INSERT INTO ALUMNOS
    VALUES (
        (SELECT MAX(COD_ALUMNO) FROM ALUMNOS)+1,
        'Pedro', 'Jimenez Lopez', '43456655L', '1ºB', 'C/ Picasso, nº12, EXTREMADURA');
        
-- EJERCICIO 2
INSERT INTO PROFESORES
    VALUES (
        (SELECT MAX(COD_PROFESOR) FROM PROFESORES)+1,
        'Montes', 'Manuel', 'manumon@gmail.com', '3ºA', 1);
        
-- EJERCICIO 3
INSERT INTO INCIDENCIAS
    VALUES (
        (SELECT MAX(COD_INCIDENCIA) FROM INCIDENCIAS)+1, 'Hablar en clase', 3, 'Ha hablado en clase, cuando debería estar callado');
INSERT INTO INCIDENCIAS
    VALUES (
        (SELECT MAX(COD_INCIDENCIA) FROM INCIDENCIAS)+1, 'Pegar a un compañero', 5, 'El alumno ha ejecutado fuerza física contra otro alumno');
INSERT INTO INCIDENCIAS
    VALUES (
        (SELECT MAX(COD_INCIDENCIA) FROM INCIDENCIAS)+1, 'Fumar hierba', 10, 'El alumno fumó hierba en clase');

-- EJERCICIO 4
INSERT INTO PARTES
    VALUES (
        (SELECT MAX(COD_PARTE) FROM PARTES)+1,
        (SELECT MAX(COD_PROFESOR) FROM PROFESORES),
        (SELECT MAX(COD_ALUMNO) FROM ALUMNOS),
        28,'Lengua','03/03/2024','2º Hora',3);
INSERT INTO PARTES
    VALUES (
        (SELECT MAX(COD_PARTE) FROM PARTES)+1,
        (SELECT MAX(COD_PROFESOR) FROM PROFESORES),
        (SELECT MAX(COD_ALUMNO) FROM ALUMNOS),
        22,'Inglés','07/03/2024','4º Hora',2);
INSERT INTO PARTES
    VALUES (
        (SELECT MAX(COD_PARTE) FROM PARTES)+1,
        (SELECT MAX(COD_PROFESOR) FROM PROFESORES),
        (SELECT MAX(COD_ALUMNO) FROM ALUMNOS),
        28,'Lengua',SYSDATE,'1º Hora',5);
        
-- EJERCICIO 5
INSERT INTO EXPULSIONES
    VALUES (
        (SELECT MAX(COD_EXPULSION) FROM EXPULSIONES)+1,
        '06/04/18',
        '09/04/18');
        
-- EJERCICIO 6
INSERT INTO PARTES_EXPULSION
    VALUES (
        (SELECT MAX(COD_PARTE_EXPULSION) FROM PARTES_EXPULSION)+1,
        (SELECT MAX(COD_EXPULSION) FROM EXPULSIONES),
        (SELECT COD_PROFESOR FROM PARTES WHERE COD_PARTE=35),
        (SELECT COD_ALUMNO FROM PARTES WHERE COD_PARTE=35),
        (SELECT COD_INCIDENCIA FROM PARTES WHERE COD_PARTE=35),
        (SELECT MATERIA_PARTE FROM PARTES WHERE COD_PARTE=35),
        (SELECT FECHA_PARTE FROM PARTES WHERE COD_PARTE=35),
        (SELECT HORA_PARTE FROM PARTES WHERE COD_PARTE=35),
        (SELECT PUNTOS_PARTE FROM PARTES WHERE COD_PARTE=35));
INSERT INTO PARTES_EXPULSION
    VALUES (
        (SELECT MAX(COD_PARTE_EXPULSION) FROM PARTES_EXPULSION)+1,
        (SELECT MAX(COD_EXPULSION) FROM EXPULSIONES),
        (SELECT COD_PROFESOR FROM PARTES WHERE COD_PARTE=36),
        (SELECT COD_ALUMNO FROM PARTES WHERE COD_PARTE=36),
        (SELECT COD_INCIDENCIA FROM PARTES WHERE COD_PARTE=36),
        (SELECT MATERIA_PARTE FROM PARTES WHERE COD_PARTE=36),
        (SELECT FECHA_PARTE FROM PARTES WHERE COD_PARTE=36),
        (SELECT HORA_PARTE FROM PARTES WHERE COD_PARTE=36),
        (SELECT PUNTOS_PARTE FROM PARTES WHERE COD_PARTE=36));        
INSERT INTO PARTES_EXPULSION
    VALUES (
        (SELECT MAX(COD_PARTE_EXPULSION) FROM PARTES_EXPULSION)+1,
        (SELECT MAX(COD_EXPULSION) FROM EXPULSIONES),
        (SELECT COD_PROFESOR FROM PARTES WHERE COD_PARTE=37),
        (SELECT COD_ALUMNO FROM PARTES WHERE COD_PARTE=37),
        (SELECT COD_INCIDENCIA FROM PARTES WHERE COD_PARTE=37),
        (SELECT MATERIA_PARTE FROM PARTES WHERE COD_PARTE=37),
        (SELECT FECHA_PARTE FROM PARTES WHERE COD_PARTE=37),
        (SELECT HORA_PARTE FROM PARTES WHERE COD_PARTE=37),
        (SELECT PUNTOS_PARTE FROM PARTES WHERE COD_PARTE=37));     
    
-- EJERCICIO 7
DELETE FROM PARTES_EXPULSION
    WHERE COD_EXPULSION=(SELECT MAX(COD_EXPULSION) FROM EXPULSIONES);
    
-- EJERCICIO 8
INSERT INTO INCIDENCIAS
    VALUES (
        (SELECT MAX(COD_INCIDENCIA) FROM INCIDENCIAS)+1,
        'Abrir Coca Cola en clase',
        10,
        'Abrir');
        
-- EJERCICIO 9
UPDATE PARTES
    SET PUNTOS_PARTE=
        CASE
            WHEN PUNTOS_PARTE=3 THEN (PUNTOS_PARTE-2)
            WHEN PUNTOS_PARTE=5 THEN (PUNTOS_PARTE-1)
            ELSE PUNTOS_PARTE
        END
    WHERE COD_ALUMNO IN
        (SELECT COD_ALUMNO FROM ALUMNOS);

-- EJERCICIO 10
UPDATE INCIDENCIAS
    SET DESCRIPCION_INCIDENCIA='Insultar'
WHERE DESCRIPCION_INCIDENCIA LIKE '%Insultar a un compañero%';

-- EJERCICIO 11
INSERT INTO ALUMNOS
    VALUES (
        (SELECT MAX(COD_ALUMNO) FROM ALUMNOS)+1,
        'Raúl',
        'Iniesta Alejo',
        '648773',
        (SELECT GRUPO_ALUMNO FROM ALUMNOS WHERE COD_ALUMNO=11),
        (SELECT DIR_ALUMNO FROM ALUMNOS WHERE COD_ALUMNO=11));
        
-- EJERCICIO 12
INSERT INTO EXPULSIONES
    SELECT 
        (SELECT MAX(COD_EXPULSION) FROM EXPULSIONES)+1,
        SYSDATE,
        SYSDATE+4
    FROM EXPULSIONES WHERE COD_EXPULSION>=ALL
        (SELECT COD_EXPULSION FROM EXPULSIONES);

-- EJERCICIO 13
INSERT INTO PARTES
    VALUES (    
        (SELECT MAX(COD_PARTE) FROM PARTES)+1,
        (SELECT COD_PROFESOR FROM PROFESORES WHERE COD_PROFESOR=11),
        (SELECT COD_ALUMNO FROM ALUMNOS WHERE COD_ALUMNO=11),
        28,
        'Informática',
        sysdate,
        '2º Hora',
        2);
        
-- EJERCICIO 14
INSERT INTO PARTES
    VALUES (
        (SELECT MAX(COD_PARTE) FROM PARTES)+1,
        (SELECT COD_PROFESOR FROM PROFESORES WHERE NOM_PROFESOR LIKE '%Pedro%'),
        (SELECT COD_ALUMNO FROM ALUMNOS WHERE NOM_ALUMNO LIKE '%Luis%'),
        (SELECT COD_INCIDENCIA FROM INCIDENCIAS WHERE NOM_INCIDENCIA LIKE '%Robo%'),
        'Matemáticas',
        SYSDATE,
        '5º Hora',
        4);
        
-- EJERCICIO 15
UPDATE PARTES
    SET COD_PROFESOR=(SELECT COD_PROFESOR FROM PROFESORES WHERE APE_PROFESOR LIKE '%Escalera%' AND NOM_PROFESOR LIKE '%Adri%')
WHERE COD_PARTE=7;

-- EJERCICIO 16
UPDATE ALUMNOS
    SET GRUPO_ALUMNO='2ºB'
WHERE NOM_ALUMNO LIKE '%Tobías%' AND APE_ALUMNO LIKE '%Lorente Sanchez%';

-- EJERCICIO 17
UPDATE ALUMNOS
    SET GRUPO_ALUMNO='2ºA'
WHERE COD_ALUMNO NOT IN 
    (SELECT COD_ALUMNO FROM PARTES);
    
-- EJERCICIO 18
DELETE FROM PARTES
    WHERE COD_INCIDENCIA IN
        (SELECT COD_INCIDENCIA FROM INCIDENCIAS)
    AND PUNTOS_PARTE<
        (SELECT PUNTOS_INCIDENCIA FROM INCIDENCIAS WHERE NOM_INCIDENCIA LIKE '%Llegar tarde a clase%');
        
-- EJERCICIO 19
DELETE FROM PARTES
    WHERE COD_PROFESOR IN
        (SELECT COD_PROFESOR FROM PROFESORES WHERE TIPO_PROFESOR=2);
        
-- EJERCICIO 20
DELETE FROM PARTES
    WHERE FECHA_PARTE BETWEEN SYSDATE AND SYSDATE-(30*6)
    AND (SELECT SUM(PUNTOS_PARTE) FROM PARTES GROUP BY COD_ALUMNO)<5;