/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bolaprueba;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author PROGRAMACION
 */
public class Prueba extends javax.swing.JFrame {

    private int x,y;
    private int calcX=2;
    private int calcY=2;
    private int velocidad=1;
    /**
     * Creates new form Prueba
     */
    public Prueba() {
        initComponents();
        
        this.setSize(600, 450);
        
        x=ObjetoAMover.getX();
        y=ObjetoAMover.getY();        
        
        Timer timer=new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                ObjetoAMover.setLocation(x, y);
                
                if((ObjetoAMover.getY()+ObjetoAMover.getHeight()) >= Contenedor.getHeight()) {
                    velocidad++;
                    calcY=-velocidad;                   
                }
                if((ObjetoAMover.getX()+ObjetoAMover.getWidth()) >= Contenedor.getWidth()) {
                    velocidad++;
                    calcX=-velocidad;     
                }
                if(ObjetoAMover.getY() == 0) {
                    velocidad++;
                    calcY=velocidad;                   
                }
                if(ObjetoAMover.getX() == 0) {
                    velocidad++;
                    calcX=velocidad;     
                }
                
                x=(x+calcX);
                y=(y+calcY);                
            }
        });
        timer.start();                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        ObjetoAMover = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));
        Contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ObjetoAMover.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout ObjetoAMoverLayout = new javax.swing.GroupLayout(ObjetoAMover);
        ObjetoAMover.setLayout(ObjetoAMoverLayout);
        ObjetoAMoverLayout.setHorizontalGroup(
            ObjetoAMoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        ObjetoAMoverLayout.setVerticalGroup(
            ObjetoAMoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        Contenedor.add(ObjetoAMover, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 20, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private javax.swing.JPanel ObjetoAMover;
    // End of variables declaration//GEN-END:variables
}
