/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica4ejercicio4;

import java.awt.Color;

/**
 *
 * @author Alfonso
 */
public class PreguntasYRespuestas extends javax.swing.JFrame {

    /**
     * Creates new form PreguntasYRespuestas
     */
    public PreguntasYRespuestas() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPregunta1 = new javax.swing.ButtonGroup();
        buttonGroupPregunta2 = new javax.swing.ButtonGroup();
        buttonGroupPregunta3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelPregunta1 = new javax.swing.JLabel();
        jRadioButtonP1_58 = new javax.swing.JRadioButton();
        jRadioButtonP1_34 = new javax.swing.JRadioButton();
        jRadioButtonP1_31 = new javax.swing.JRadioButton();
        jRadioButtonP1_40 = new javax.swing.JRadioButton();
        jLabelValor1 = new javax.swing.JLabel();
        jLabelPregunta2 = new javax.swing.JLabel();
        jRadioButtonP2_Marte = new javax.swing.JRadioButton();
        jRadioButtonP2_Jupiter = new javax.swing.JRadioButton();
        jRadioButtonP2_Tierra = new javax.swing.JRadioButton();
        jRadioButtonP2_Saturno = new javax.swing.JRadioButton();
        jLabelValor2 = new javax.swing.JLabel();
        jLabelPregunta3 = new javax.swing.JLabel();
        jRadioButtonP3_ola = new javax.swing.JRadioButton();
        jRadioButtonP3_desicion = new javax.swing.JRadioButton();
        jRadioButtonP3_hay = new javax.swing.JRadioButton();
        jLabelValor3 = new javax.swing.JLabel();
        jRadioButtonP3_ahi = new javax.swing.JRadioButton();
        jLabelPregunta4 = new javax.swing.JLabel();
        jLabelValor4 = new javax.swing.JLabel();
        jCheckBox_sagaz = new javax.swing.JCheckBox();
        jCheckBox_listo = new javax.swing.JCheckBox();
        jCheckBox_lerdo = new javax.swing.JCheckBox();
        jCheckBox_astuto = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(102, 102, 255));
        jLabelTitulo.setText("Ingrese la respuesta correcta");

        jLabelPregunta1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelPregunta1.setForeground(new java.awt.Color(102, 102, 255));
        jLabelPregunta1.setText("4*6+3+2*2");

        buttonGroupPregunta1.add(jRadioButtonP1_58);
        jRadioButtonP1_58.setText("58");

        buttonGroupPregunta1.add(jRadioButtonP1_34);
        jRadioButtonP1_34.setText("34");

        buttonGroupPregunta1.add(jRadioButtonP1_31);
        jRadioButtonP1_31.setText("31");

        buttonGroupPregunta1.add(jRadioButtonP1_40);
        jRadioButtonP1_40.setText("40");

        jLabelValor1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelValor1.setForeground(new java.awt.Color(102, 102, 255));
        jLabelValor1.setText("Valor");

        jLabelPregunta2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelPregunta2.setForeground(new java.awt.Color(102, 102, 255));
        jLabelPregunta2.setText("Nombre del quinto planeta");

        buttonGroupPregunta2.add(jRadioButtonP2_Marte);
        jRadioButtonP2_Marte.setText("Marte");

        buttonGroupPregunta2.add(jRadioButtonP2_Jupiter);
        jRadioButtonP2_Jupiter.setText("Jupiter");

        buttonGroupPregunta2.add(jRadioButtonP2_Tierra);
        jRadioButtonP2_Tierra.setText("La Tierra");

        buttonGroupPregunta2.add(jRadioButtonP2_Saturno);
        jRadioButtonP2_Saturno.setText("Saturno");
        jRadioButtonP2_Saturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonP2_SaturnoActionPerformed(evt);
            }
        });

        jLabelValor2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelValor2.setForeground(new java.awt.Color(102, 102, 255));
        jLabelValor2.setText("Valor");

        jLabelPregunta3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelPregunta3.setForeground(new java.awt.Color(102, 102, 255));
        jLabelPregunta3.setText("Palabra con error ortográfico");

        buttonGroupPregunta3.add(jRadioButtonP3_ola);
        jRadioButtonP3_ola.setText("ola");

        buttonGroupPregunta3.add(jRadioButtonP3_desicion);
        jRadioButtonP3_desicion.setText("desición");

        buttonGroupPregunta3.add(jRadioButtonP3_hay);
        jRadioButtonP3_hay.setText("hay");

        jLabelValor3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelValor3.setForeground(new java.awt.Color(102, 102, 255));
        jLabelValor3.setText("Valor");

        buttonGroupPregunta3.add(jRadioButtonP3_ahi);
        jRadioButtonP3_ahi.setText("ahí");

        jLabelPregunta4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelPregunta4.setForeground(new java.awt.Color(102, 102, 255));
        jLabelPregunta4.setText("Sinónimos de inteligente");

        jLabelValor4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelValor4.setForeground(new java.awt.Color(102, 102, 255));
        jLabelValor4.setText("Valor");

        jCheckBox_sagaz.setText("sagaz");
        jCheckBox_sagaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_sagazActionPerformed(evt);
            }
        });

        jCheckBox_listo.setText("listo");

        jCheckBox_lerdo.setText("lerdo");

        jCheckBox_astuto.setText("astuto");

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("MOSTRAR");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPregunta2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPregunta1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelValor2)
                            .addComponent(jLabelValor1)
                            .addComponent(jLabelValor3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButtonP1_58)
                                            .addComponent(jRadioButtonP1_34))
                                        .addGap(90, 90, 90)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButtonP1_40)
                                            .addComponent(jRadioButtonP1_31)))
                                    .addComponent(jRadioButtonP2_Jupiter)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonP2_Marte)
                                        .addGap(70, 70, 70)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButtonP2_Saturno)
                                            .addComponent(jRadioButtonP2_Tierra)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)))
                                .addContainerGap(112, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelPregunta4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelValor4)
                                .addGap(36, 36, 36))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPregunta3)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jRadioButtonP3_ola)
                                                    .addComponent(jRadioButtonP3_desicion))
                                                .addGap(51, 51, 51)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jRadioButtonP3_ahi)
                                                    .addComponent(jRadioButtonP3_hay)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jCheckBox_sagaz)
                                                    .addComponent(jCheckBox_listo))
                                                .addGap(71, 71, 71)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jCheckBox_astuto)
                                                    .addComponent(jCheckBox_lerdo))))))
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPregunta1)
                    .addComponent(jLabelValor1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonP1_58)
                    .addComponent(jRadioButtonP1_31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonP1_34)
                    .addComponent(jRadioButtonP1_40))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPregunta2)
                    .addComponent(jLabelValor2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonP2_Marte)
                    .addComponent(jRadioButtonP2_Tierra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonP2_Jupiter)
                    .addComponent(jRadioButtonP2_Saturno))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPregunta3)
                    .addComponent(jLabelValor3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonP3_ola)
                    .addComponent(jRadioButtonP3_hay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonP3_desicion)
                    .addComponent(jRadioButtonP3_ahi))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPregunta4)
                    .addComponent(jLabelValor4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_sagaz)
                    .addComponent(jCheckBox_lerdo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_listo)
                    .addComponent(jCheckBox_astuto))
                .addGap(33, 33, 33)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonP2_SaturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonP2_SaturnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonP2_SaturnoActionPerformed

    private void jCheckBox_sagazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_sagazActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_sagazActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Color color=new Color(0,153,0);

        // Primera pregunta
        if(jRadioButtonP1_31.isSelected()) {
            jLabelValor1.setText("BIEN");
            jLabelValor1.setForeground(color);            
        } else {
            jLabelValor1.setText("MAL");
            jLabelValor1.setForeground(Color.red);
        }
        
        // Segunda pregunta
        if(jRadioButtonP2_Jupiter.isSelected()) {
            jLabelValor2.setText("BIEN");
            jLabelValor2.setForeground(color);  
        } else {
            jLabelValor2.setText("MAL");
            jLabelValor2.setForeground(Color.red);
        }
        
        // Tercera pregunta
        if(jRadioButtonP3_desicion.isSelected()) {
            jLabelValor3.setText("BIEN");
            jLabelValor3.setForeground(color);  
        } else {
            jLabelValor3.setText("MAL");
            jLabelValor3.setForeground(Color.red);
        }
        
        // Cuarta pregunta
        if(jCheckBox_astuto.isSelected() && jCheckBox_listo.isSelected() && jCheckBox_sagaz.isSelected() && !jCheckBox_lerdo.isSelected()) {
            jLabelValor4.setText("BIEN");
            jLabelValor4.setForeground(color);
        } else if(jCheckBox_astuto.isSelected() && jCheckBox_listo.isSelected() || jCheckBox_sagaz.isSelected() && jCheckBox_listo.isSelected() || jCheckBox_astuto.isSelected() && jCheckBox_sagaz.isSelected()) {
            if(!jCheckBox_lerdo.isSelected()) {
                jLabelValor4.setText("REGULAR");
                jLabelValor4.setForeground(Color.orange);   
            } else {
                jLabelValor4.setText("MAL");
                jLabelValor4.setForeground(Color.red);
            }
        } else if(jCheckBox_astuto.isSelected() || jCheckBox_listo.isSelected() || jCheckBox_sagaz.isSelected()) {
            if(!jCheckBox_lerdo.isSelected()) {
                jLabelValor4.setText("REGULAR");
                jLabelValor4.setForeground(Color.orange);   
            } else {
                jLabelValor4.setText("MAL");
                jLabelValor4.setForeground(Color.red);
            }
        } else {
            jLabelValor4.setText("MAL");
            jLabelValor4.setForeground(Color.red);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreguntasYRespuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreguntasYRespuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreguntasYRespuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreguntasYRespuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreguntasYRespuestas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupPregunta1;
    private javax.swing.ButtonGroup buttonGroupPregunta2;
    private javax.swing.ButtonGroup buttonGroupPregunta3;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox_astuto;
    private javax.swing.JCheckBox jCheckBox_lerdo;
    private javax.swing.JCheckBox jCheckBox_listo;
    private javax.swing.JCheckBox jCheckBox_sagaz;
    private javax.swing.JLabel jLabelPregunta1;
    private javax.swing.JLabel jLabelPregunta2;
    private javax.swing.JLabel jLabelPregunta3;
    private javax.swing.JLabel jLabelPregunta4;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelValor1;
    private javax.swing.JLabel jLabelValor2;
    private javax.swing.JLabel jLabelValor3;
    private javax.swing.JLabel jLabelValor4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonP1_31;
    private javax.swing.JRadioButton jRadioButtonP1_34;
    private javax.swing.JRadioButton jRadioButtonP1_40;
    private javax.swing.JRadioButton jRadioButtonP1_58;
    private javax.swing.JRadioButton jRadioButtonP2_Jupiter;
    private javax.swing.JRadioButton jRadioButtonP2_Marte;
    private javax.swing.JRadioButton jRadioButtonP2_Saturno;
    private javax.swing.JRadioButton jRadioButtonP2_Tierra;
    private javax.swing.JRadioButton jRadioButtonP3_ahi;
    private javax.swing.JRadioButton jRadioButtonP3_desicion;
    private javax.swing.JRadioButton jRadioButtonP3_hay;
    private javax.swing.JRadioButton jRadioButtonP3_ola;
    // End of variables declaration//GEN-END:variables
}
