--Borrado de tablas
DROP TABLE PARTIDOS CASCADE CONSTRAINTS; 
DROP TABLE MASCOTAS CASCADE CONSTRAINTS;
DROP TABLE EQUIPOS CASCADE CONSTRAINTS;
DROP TABLE JUGADORES CASCADE CONSTRAINTS;
DROP TABLE ANILLOS CASCADE CONSTRAINTS;
DROP TABLE JUEGAN CASCADE CONSTRAINTS;
DROP TABLE INTEGRANTES CASCADE CONSTRAINTS;
DROP TABLE TIENEN CASCADE CONSTRAINTS; 

--TABLA PARTIDOS
--Creación 
CREATE TABLE PARTIDOS (
    cod_partido NUMBER(10),
    resultado VARCHAR2(10) NOT NULL,
    fecha DATE NOT NULL,
    estadio VARCHAR2(50) NOT NULL,
    equipo_local VARCHAR2(30) NOT NULL,
    equipo_visitante VARCHAR2(30) NOT NULL,
    CONSTRAINT par_cod_FK PRIMARY KEY(cod_partido)
);

--Inserciones 
INSERT INTO PARTIDOS VALUES('3245676543','102-30',TO_DATE('2023-10-28','YYYY-MM-DD'),'Madison Square Garden','New York Knicks','Boston Celtis');
INSERT INTO PARTIDOS VALUES('6785676642','99-100',TO_DATE('2023-10-29','YYYY-MM-DD'),'Barclays Center','Brooklyn Nets','Utah Jazz');
INSERT INTO PARTIDOS VALUES('6875746527','101-98',TO_DATE('2023-10-30','YYYY-MM-DD'),'Ball Arena','Denver Nuggets','Los Angeles Lakers');
INSERT INTO PARTIDOS VALUES('7855446642','140-60',TO_DATE('2023-10-31','YYYY-MM-DD'),'Delta Center','Utah Jazz','Washington Wizards');

--TABLA MASCOTAS
--Creación
CREATE TABLE MASCOTAS(
    nombre VARCHAR2(100) NOT NULL,
    id_mascota VARCHAR2(10),
    CONSTRAINT mas_cod_PK PRIMARY KEY(id_mascota)
);

--Inserciones
INSERT INTO MASCOTAS VALUES('nevado',0000000001);
INSERT INTO MASCOTAS VALUES('pepe',0000000002);

--TABLA EQUIPOS
--Creación
CREATE TABLE EQUIPOS(
    nombre_equipo VARCHAR2(50) NOT NULL,
    ciudad VARCHAR2(50) NOT NULL,
    conferencia VARCHAR2(10) NOT NULL,
    num_mpvs VARCHAR2(5) NOT NULL,
    num_campeonatos VARCHAR2(5) NOT NULL,  
    codigo_equipo NUMBER(10),
    id_mascota VARCHAR2(10)DEFAULT '',
    CONSTRAINT equ_cod_PK PRIMARY KEY(codigo_equipo),
    CONSTRAINT equ_con_CK CHECK (conferencia IN('Este','Oeste')),
    CONSTRAINT equ_mas_FK FOREIGN KEY (id_mascota) REFERENCES MASCOTAS ON DELETE CASCADE
);

--Inserciones
INSERT INTO EQUIPOS VALUES('Utah Jazz','Salt Lake City','Oeste','0','0',000004,0000000001);
INSERT INTO EQUIPOS VALUES ('Angeles Lakers','Los Ángeles','Oeste','1','17',00001,0000000002);
INSERT INTO EQUIPOS VALUES ('Angeles Clipper','Los Ángeles','Oeste','3','7',00002,'');
INSERT INTO EQUIPOS VALUES ('Boston Celtics','Boston','Este','0','17',00003,'');

--TABLA JUGADORES
--Creación
CREATE TABLE JUGADORES(
    Nombre_jugador VARCHAR2(100) NOT NULL,
    Apellidos_jugador VARCHAR2(100) NOT NULL,
    Edad_jugador NUMBER(3) NOT NULL,
    Posicion VARCHAR2(20) NOT NULL,
    Altura NUMBER(4,2) NOT NULL,
    Peso NUMBER(5,2) NOT NULL,
    DNI_mentor VARCHAR2(9) DEFAULT '',
    codigo_equipo NUMBER(10) NOT NULL,
    DNI_jugador VARCHAR2(9),
    CONSTRAINT jug_dni_PK PRIMARY KEY (DNI_jugador),
    CONSTRAINT jug_dnm_FK FOREIGN KEY (DNI_mentor) REFERENCES JUGADORES(DNI_jugador) ON DELETE CASCADE,
    CONSTRAINT jug_cod_FK FOREIGN KEY (codigo_equipo) REFERENCES EQUIPOS ON DELETE CASCADE,
    CONSTRAINT jug_pos_CK CHECK (Posicion IN('Base','Escolta','Alero','Pivot','Ala-pivot'))
);

--Inserciones
-- Inserciones en la tabla JUGADORES
INSERT INTO JUGADORES VALUES('Donovan','Mitchell',26,'Escolta',1.91,98, '',000004,'46293649J');
INSERT INTO JUGADORES VALUES('Stephen','Curry',35,'Base',1.88,84.75,'46293649J',000004,'68351936L');
INSERT INTO JUGADORES VALUES('Luka','Doncic',23,'Base',2.01,99.5,'',000001,'04528353L');
INSERT INTO JUGADORES VALUES('Giannis','Antetokounmpo',28,'Ala-pivot',2.11,120.3,'',000002,'04529352K');
INSERT INTO JUGADORES VALUES('Kevin','Durant',34,'Alero',2.08,109,'',000003,'74926492P');

--TABLA ANILLOS
--Creación
CREATE TABLE ANILLOS (
    Fecha_asignacion DATE NOT NULL,
    DNI_jugador VARCHAR(9),
    Numero_anillo NUMBER(5),
    CONSTRAINT ani_PK PRIMARY KEY (DNI_jugador,Numero_anillo),
    CONSTRAINT ani_dni_FK FOREIGN KEY (DNI_jugador) REFERENCES JUGADORES ON DELETE CASCADE
);

---Inserciones
INSERT INTO ANILLOS VALUES(TO_DATE('2012-12-11', 'YYYY-MM-DD'), '46293649J', 1);
INSERT INTO ANILLOS VALUES(TO_DATE('2012-12-11', 'YYYY-MM-DD'), '68351936L', 1);
INSERT INTO ANILLOS VALUES(TO_DATE('2014-08-23', 'YYYY-MM-DD'), '04528353L', 4);

--TABLA JUEGAN
--Creación
CREATE TABLE JUEGAN(
    cod_partido NUMBER(10),
    DNI_jugador VARCHAR2(9),
    codigo_equipo NUMBER(10) NOT NULL,
    CONSTRAINT jue_cod_PK PRIMARY KEY (cod_partido, DNI_jugador),
    CONSTRAINT dni_jue_FK FOREIGN KEY (DNI_jugador) REFERENCES JUGADORES ON DELETE CASCADE,
    CONSTRAINT par_jue_FK FOREIGN KEY (cod_partido) REFERENCES PARTIDOS ON DELETE CASCADE,
    CONSTRAINT equ_jue_FK FOREIGN KEY (codigo_equipo) REFERENCES EQUIPOS ON DELETE CASCADE
);

--Inserciones
INSERT INTO JUEGAN VALUES(3245676543,'74926492P',000003);
INSERT INTO JUEGAN VALUES(6785676642,'46293649J',000004);
INSERT INTO JUEGAN VALUES(7855446642,'46293649J',000004);

--TABLA INTEGRANTES
--Creación
CREATE TABLE INTEGRANTES (
    Puesto VARCHAR2(20) NOT NULL,
    Nombre_integrante VARCHAR2(100) NOT NULL,
    Apellidos_integrante VARCHAR2(100) NOT NULL,
    Calle_integrante VARCHAR2(100) NOT NULL,
    Ciudad_integrante VARCHAR2(50) NOT NULL,
    Numero_integrante NUMBER(5) NOT NULL,
    Telefono_integrante NUMBER(9) NOT NULL,
    Num_licencia NUMBER(10) DEFAULT 0,
    DNI_integrante VARCHAR2(9),
    CONSTRAINT int_dni_PK PRIMARY KEY(DNI_integrante),
    CONSTRAINT int_pue_CK CHECK (Puesto IN('Fisios','Asistentes','Otros'))
);

--Inserciones
INSERT INTO INTEGRANTES VALUES ('Fisios','Juan','Pérez','Calle Mayor','Madrid',1234,654321789,123456789,'12345678A');
INSERT INTO INTEGRANTES VALUES('Asistentes','Ana','García','Calle del Sol','Barcelona',5678,987654321,0,'98765432B');
INSERT INTO INTEGRANTES VALUES('Otros','Pedro','López','Calle de la Paz','Sevilla',9012,213456789,0,'32145678C');
      
--TABLA TIENEN
--Creación
CREATE TABLE TIENEN (
    codigo_equipo NUMBER(10),
    DNI_integrante VARCHAR2(9),
    fecha DATE,
    CONSTRAINT tie_PK PRIMARY KEY(fecha, codigo_equipo, DNI_integrante),
    CONSTRAINT tie_equ_FK FOREIGN KEY(codigo_equipo) REFERENCES EQUIPOS ON DELETE CASCADE,
    CONSTRAINT tie_dni_fk FOREIGN KEY(DNI_integrante) REFERENCES INTEGRANTES ON DELETE CASCADE
);

--Inserciones
INSERT INTO TIENEN VALUES(000004,'12345678A',TO_DATE('2014-08-23', 'YYYY-MM-DD'));
INSERT INTO TIENEN VALUES(000004,'32145678C',TO_DATE('2014-1-20', 'YYYY-MM-DD'));
INSERT INTO TIENEN VALUES(000002,'98765432B',TO_DATE('2014-08-23', 'YYYY-MM-DD'));


